### ISSUE TITLE
Dear Thomas, the Windows standalone exe is not working it seems.

### ISSUE THREAD

**Issue by puuffff** [maaaaz/tibcopasswordrevealer#1]
I am using  Win 10 and no matter which compatible mode I choose. The windows standalone exe is just not working...

**Comment by maaaaz** [comment]
Hello,

This is weird, it is fully working for me. Which error do you encounter ?

**Comment by puuffff** [comment]
When I try opening it, it just makes a splash of terminal/CMD like window and quickly exits itself.

**Comment by puuffff** [comment]
Dear Thomas,

Quite Sorry... I have not been looking at the ReadMe clearly. I now understand it is supposed to run from command line and not a GUI way. 
Closing the 'issue' now

Thanks,
Kevin
